In [65]:
import pandas as pd
import numpy as np
bias_data = np.genfromtxt("https://raw.githubusercontent.com/yeshiva-analytics-programming/datasets/master/nyc_311_bias.csv",
                          delimiter = ",",
                          skip_header = 1)

In [66]:
bias_data

array([[3.60050001e+10, 1.10910000e+04, 1.10910000e+04, ...,
        3.77900000e+03, 1.72400000e+03, 3.08000000e+01],
       [3.60050002e+10, 4.33400000e+03, 4.33400000e+03, ...,
        2.99300000e+03, 1.33200000e+03, 3.28000000e+01],
       [3.60050004e+10, 5.50300000e+03, 5.50300000e+03, ...,
        3.75500000e+03, 1.49700000e+03, 3.46000000e+01],
       ...,
       [3.60850319e+10, 4.84800000e+03, 4.84800000e+03, ...,
        1.49800000e+03, 9.97000000e+02, 2.67000000e+01],
       [3.60850323e+10, 1.25000000e+03, 1.25000000e+03, ...,
        4.42000000e+02, 4.85000000e+02, 3.39000000e+01],
       [3.60859901e+10, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [67]:
bias_data[:,1] == bias_data[:,2]

array([ True,  True,  True, ...,  True,  True,  True])

In [68]:
sum(bias_data[:,1] != bias_data[:,2])

0

In [69]:
pct_white = np.divide(bias_data[:,5],bias_data[:,1])*100

/Users/harisx91/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [70]:
bias_data[:,1]

array([11091.,  4334.,  5503., ...,  4848.,  1250.,     0.])

In [71]:
bias_data[:,1].min()

0.0

In [72]:
pct_white 

array([15.54413488, 30.73373327, 27.20334363, ..., 20.56518152,
       38.8       ,         nan])

In [73]:
bias_data = np.column_stack((bias_data, pct_white))

In [74]:
bias_data

array([[3.60050001e+10, 1.10910000e+04, 1.10910000e+04, ...,
        1.72400000e+03, 3.08000000e+01, 1.55441349e+01],
       [3.60050002e+10, 4.33400000e+03, 4.33400000e+03, ...,
        1.33200000e+03, 3.28000000e+01, 3.07337333e+01],
       [3.60050004e+10, 5.50300000e+03, 5.50300000e+03, ...,
        1.49700000e+03, 3.46000000e+01, 2.72033436e+01],
       ...,
       [3.60850319e+10, 4.84800000e+03, 4.84800000e+03, ...,
        9.97000000e+02, 2.67000000e+01, 2.05651815e+01],
       [3.60850323e+10, 1.25000000e+03, 1.25000000e+03, ...,
        4.85000000e+02, 3.39000000e+01, 3.88000000e+01],
       [3.60859901e+10, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00,            nan]])

In [77]:
my_arr = np.arange(1000000)

In [78]:
my_list = list(range(1000000))

In [80]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 20.9 ms, sys: 6.21 ms, total: 27.1 ms
Wall time: 29.5 ms


In [81]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 566 ms, sys: 147 ms, total: 713 ms
Wall time: 712 ms


In [85]:
#generate some random data
data = np.random.randn(2,3)

In [86]:
data

array([[ 0.10699045, -0.9581436 ,  0.72423573],
       [-0.79712707,  0.78164046, -0.17948651]])

In [87]:
data * 10

array([[ 1.06990453, -9.58143599,  7.24235729],
       [-7.97127075,  7.81640464, -1.79486511]])

In [88]:
data + data

array([[ 0.21398091, -1.9162872 ,  1.44847146],
       [-1.59425415,  1.56328093, -0.35897302]])

In [89]:
data * 2

array([[ 0.21398091, -1.9162872 ,  1.44847146],
       [-1.59425415,  1.56328093, -0.35897302]])

In [90]:
data.shape

(2, 3)

In [91]:
data.dtype

dtype('float64')

In [92]:
data1 = [6,7.5,8,0,1]

In [93]:
arr1 = np.array(data1)

In [104]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [110]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [111]:
arr2 = np.array(data2)

In [112]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [113]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
arr2.ndim

2

In [115]:
arr2.shape

(2, 4)

In [117]:
arr1.dtype

dtype('float64')

In [118]:
arr2.dtype

dtype('int64')

In [120]:
#pass a tuple for the shape
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [130]:
np.zeros((2, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [150]:
#create 2 list, with 4 rows and 2 columns. 
np.empty((2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [152]:
arrange= np.arange(15)

In [153]:
arrange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [154]:
arr1 = np.array([1,2,3], dtype=np.float)

In [155]:
arr2 = np.array([1,2,3], dtype=np.int32)

In [156]:
arr1.dtype

dtype('float64')

In [158]:
arr2.dtype

dtype('int32')

In [165]:
arr = np.array([1,2,3,4,5])

In [166]:
arr.dtype

dtype('int64')

In [167]:
float_arr= arr.astype(np.float64)

In [168]:
float_arr.dtype

dtype('float64')

In [169]:
float_arr

array([1., 2., 3., 4., 5.])

In [170]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [171]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [175]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [176]:
numeric_string = np.array(['1.24', '-9.6','42'], dtype=np.string_)

In [177]:
numeric_string.astype(float)

array([ 1.24, -9.6 , 42.  ])

In [203]:
int_array = np.arange(10)

In [204]:
calibers = np.array([.22, .270,.357,.380, .44, .50], dtype = np.float64)

In [205]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [206]:
empty_uint32 = np.empty(8, dtype='u4')

In [207]:
empty_uint32

array([         0, 1073741824, 1137830371, 1073743870,         14,
                0,          0,          0], dtype=uint32)

In [210]:
arr = np.array([[1.,2.,3.], [4.,5.,6.]])

In [211]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [212]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [213]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [214]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [215]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [216]:
arr2= np.array([[0.,4.,1.], [7.,2.,12.]])

In [217]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [220]:
#Evaluating operations between different sized array is called Broadcasting
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [222]:
arr = np.arange(10)

In [223]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [224]:
arr[5]

5

In [225]:
arr[5:8]

array([5, 6, 7])

In [226]:
arr[5:8] = 12

In [227]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [228]:
arr_slice = arr[5:8]

In [229]:
arr_slice

array([12, 12, 12])

In [230]:
arr_slice[1]=12345

In [231]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [232]:
arr_slice[:] = 64

In [267]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [268]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [269]:
arr2d[2]

array([7, 8, 9])

In [270]:
arr2d[0][2]

3

In [271]:
arr2d[0,2]

3

In [272]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [273]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [274]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [275]:
old_values = arr3d[0].copy()

In [276]:
arr3d[0] = 42

In [277]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [278]:
arr3d[0] = old_values

In [279]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [280]:
arr3d[1,0]

array([7, 8, 9])

In [281]:
x = arr3d[1]

In [282]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [283]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [284]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [285]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [286]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [287]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [289]:
#Select the second row but only first two columns
arr2d[1,:2]

array([4, 5])

In [293]:
arr2d[:2,2]

array([3, 6])

In [294]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [301]:
arr2d

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

In [302]:
arr2d

array([[0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

In [363]:
names = np.array(['Bob', 'Joe','Will','Bob','Will','Joe','Joe'])

In [364]:
data = np.random.randn(7,4)

In [365]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [366]:
data

array([[ 1.29176185, -1.11284616,  1.15982563, -1.78315748],
       [-2.03835575, -0.1372491 ,  0.375562  ,  0.72100848],
       [ 1.73607148, -2.04390295, -0.42552447,  1.71379157],
       [ 1.23581071, -0.4076829 ,  0.78224929, -1.15011258],
       [-0.47346559,  1.10983549,  1.17715923,  1.1836378 ],
       [-0.51961063,  1.37121844, -1.71978066, -1.16989077],
       [ 0.23475943,  1.08572344, -0.64020716,  0.52486123]])

In [367]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [368]:
data[names == 'Bob']

array([[ 1.29176185, -1.11284616,  1.15982563, -1.78315748],
       [ 1.23581071, -0.4076829 ,  0.78224929, -1.15011258]])

In [369]:
data[names == 'Bob', 2:]

array([[ 1.15982563, -1.78315748],
       [ 0.78224929, -1.15011258]])

In [370]:
data[names == 'Bob', 3]

array([-1.78315748, -1.15011258])

In [371]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [372]:
data[~(names == 'Bob')]

array([[-2.03835575, -0.1372491 ,  0.375562  ,  0.72100848],
       [ 1.73607148, -2.04390295, -0.42552447,  1.71379157],
       [-0.47346559,  1.10983549,  1.17715923,  1.1836378 ],
       [-0.51961063,  1.37121844, -1.71978066, -1.16989077],
       [ 0.23475943,  1.08572344, -0.64020716,  0.52486123]])

In [373]:
mask = (names == 'Bob') | (names == 'Will')

In [374]:
mask

array([ True, False,  True,  True,  True, False, False])

In [375]:
data[mask]

array([[ 1.29176185, -1.11284616,  1.15982563, -1.78315748],
       [ 1.73607148, -2.04390295, -0.42552447,  1.71379157],
       [ 1.23581071, -0.4076829 ,  0.78224929, -1.15011258],
       [-0.47346559,  1.10983549,  1.17715923,  1.1836378 ]])

In [376]:
data[~(mask == 'Will')]

/Users/harisx91/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  """Entry point for launching an IPython kernel.


array([ 0.23475943,  1.08572344, -0.64020716,  0.52486123])

In [377]:
data[data < 0] = 0

In [378]:
data

array([[1.29176185, 0.        , 1.15982563, 0.        ],
       [0.        , 0.        , 0.375562  , 0.72100848],
       [1.73607148, 0.        , 0.        , 1.71379157],
       [1.23581071, 0.        , 0.78224929, 0.        ],
       [0.        , 1.10983549, 1.17715923, 1.1836378 ],
       [0.        , 1.37121844, 0.        , 0.        ],
       [0.23475943, 1.08572344, 0.        , 0.52486123]])

In [379]:
data[names != 'Joe'] = 7

In [380]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.375562  , 0.72100848],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.37121844, 0.        , 0.        ],
       [0.23475943, 1.08572344, 0.        , 0.52486123]])

In [382]:
arr = np.empty((8,4))

In [384]:
for i in range (8):
    arr[i] = i

In [385]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [386]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [387]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [388]:
arr = np.arange(32).reshape(8,4)

In [389]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [390]:
arr[[1,5,7,2], [0,3,1,2]]

array([ 4, 23, 29, 10])

In [391]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [392]:
arr = np.arange(15).reshape(3,5)

In [393]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [394]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [395]:
arr = np.random.randn(6,3)

In [396]:
arr

array([[ 1.83744306, -0.60911364, -0.88857183],
       [-0.06018134, -0.98003512, -0.43624843],
       [-0.16089073,  0.33694176, -2.10760417],
       [-1.280738  , -0.12330587,  0.30708548],
       [ 0.88048016,  0.22804505, -0.24648527],
       [-0.59834494,  0.17539746, -1.00336164]])

In [397]:
np.dot(arr.T, arr)

array([[ 6.17925642, -0.86067914, -1.27731723],
       [-0.86067914,  1.54299116, -0.01142211],
       [-1.27731723, -0.01142211,  6.58365899]])

In [400]:
arr = np.arange(16).reshape((2,2,4))

In [401]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [409]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [410]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [411]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [412]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [413]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [415]:
np.zeros([5,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [420]:
a = np.arange()

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [418]:
a

array([3, 2])

In [422]:
trans = np.arange(6).reshape(3,2)

In [423]:
trans

array([[0, 1],
       [2, 3],
       [4, 5]])

In [424]:
np.transpose(trans)

array([[0, 2, 4],
       [1, 3, 5]])