In [45]:
import pandas as pd
import numpy as np

In [46]:
from pandas import Series, DataFrame

In [56]:
obj = pd.Series([4,7,-5,3])

In [57]:
obj #shows the index on the left and calues on the right column

0    4
1    7
2   -5
3    3
dtype: int64

In [58]:
obj.values

array([ 4,  7, -5,  3])

In [59]:
obj.index #to see where it starts and ends like range function

RangeIndex(start=0, stop=4, step=1)

In [64]:
obj2 = pd.Series(('4','7', '1','9'), index=['d','b','a','c'])

In [65]:
obj2

d    4
b    7
a    1
c    9
dtype: object

In [66]:
myobj = pd.Series(['1','2','3','4'])

In [67]:
obj2.values

array(['4', '7', '1', '9'], dtype=object)

In [68]:
obj2['a']

'1'

In [69]:
obj2['d'] = 6

In [70]:
obj2

d    6
b    7
a    1
c    9
dtype: object

In [71]:
obj2[['b','a','c']]

b    7
a    1
c    9
dtype: object

In [74]:
obj2[obj2>0]

TypeError: '>' not supported between instances of 'str' and 'int'

In [73]:
obj2 * 2

d    12
b    77
a    11
c    99
dtype: object

In [28]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [29]:
'b' in obj2

True

In [30]:
'e' in obj2

False

In [39]:
'6' in obj2

False

In [75]:
sdata = {'Ohio': 35000, 'Texas' : 71000, 'Oregon': 16000, 'Utah':5000}

In [76]:
obj3 = pd.Series(sdata)

In [79]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [80]:
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [81]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [82]:
onj4 = pd.Series(sdata, index=states)

In [83]:
onj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [85]:
pd.isnull(onj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [86]:
pd.notnull(onj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [87]:
onj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [88]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [89]:
onj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [90]:
obj3 + onj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [93]:
onj4.name ='population'

In [94]:
onj4.index.name = 'state'

In [95]:
onj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [96]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [97]:
obj.index= ['Bob','Steve','Jeff','Ryan']

In [98]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [100]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001,2002,2003,2004,2005],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [104]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2003  2.4
4  Nevada  2004  2.9
5  Nevada  2005  3.2

In [106]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2003  Nevada  2.4
4  2004  Nevada  2.9
5  2005  Nevada  3.2

In [110]:
frame2 = pd.DataFrame( data, columns=['year', 'city', 'state'],
                     index = ['one','two', 'three', 'four', 'five', 'six'])

In [111]:
frame2

year city   state
one    2000  NaN    Ohio
two    2001  NaN    Ohio
three  2002  NaN    Ohio
four   2003  NaN  Nevada
five   2004  NaN  Nevada
six    2005  NaN  Nevada

In [115]:
frame2.columns

Index(['year', 'city', 'state'], dtype='object')

In [116]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [117]:
frame2.year

one      2000
two      2001
three    2002
four     2003
five     2004
six      2005
Name: year, dtype: int64

In [118]:
frame2.loc['three']

year     2002
city      NaN
state    Ohio
Name: three, dtype: object

In [119]:
frame2['city'] = 'Locating'

In [122]:
frame2

year      city   state
one    2000  Locating    Ohio
two    2001  Locating    Ohio
three  2002  Locating    Ohio
four   2003  Locating  Nevada
five   2004  Locating  Nevada
six    2005  Locating  Nevada

In [123]:
frame2['city'] = np.arange(6.0)

In [124]:
frame2

year  city   state
one    2000   0.0    Ohio
two    2001   1.0    Ohio
three  2002   2.0    Ohio
four   2003   3.0  Nevada
five   2004   4.0  Nevada
six    2005   5.0  Nevada

In [129]:
val= pd.DataFrame(['1.2','1.6','1.9'], index = ['two', 'four', 'six'])

In [131]:
frame2['city'] = val

In [132]:
frame2

year city   state
one    2000  NaN    Ohio
two    2001  1.2    Ohio
three  2002  NaN    Ohio
four   2003  1.6  Nevada
five   2004  NaN  Nevada
six    2005  1.9  Nevada

In [133]:
frame2['eastern'] = frame2.state == 'Ohio'

In [134]:
frame2

year city   state  eastern
one    2000  NaN    Ohio     True
two    2001  1.2    Ohio     True
three  2002  NaN    Ohio     True
four   2003  1.6  Nevada    False
five   2004  NaN  Nevada    False
six    2005  1.9  Nevada    False

In [135]:
del frame2['eastern']

In [136]:
frame2

year city   state
one    2000  NaN    Ohio
two    2001  1.2    Ohio
three  2002  NaN    Ohio
four   2003  1.6  Nevada
five   2004  NaN  Nevada
six    2005  1.9  Nevada

In [137]:
frame2.columns

Index(['year', 'city', 'state'], dtype='object')

In [138]:
pop = {"Nevada": {2001: 2.4, 2002: 2.9}, 
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [145]:
frame3 = pd.DataFrame(pop)

In [146]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [155]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [157]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [158]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [159]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [160]:
frame2.values

array([[2000, nan, 'Ohio'],
       [2001, '1.2', 'Ohio'],
       [2002, nan, 'Ohio'],
       [2003, '1.6', 'Nevada'],
       [2004, nan, 'Nevada'],
       [2005, '1.9', 'Nevada']], dtype=object)

In [161]:
obj = pd.Series(range(3), index=['a','b','c'])

In [163]:
index = obj.index

In [164]:
index

Index(['a', 'b', 'c'], dtype='object')

In [165]:
index[1:]

Index(['b', 'c'], dtype='object')

In [166]:
index[:2]

Index(['a', 'b'], dtype='object')

In [169]:
labels  = pd.Index(np.arange(3))

In [170]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [178]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)

In [179]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [184]:
obj2.index.name = "Numbers"

In [185]:
obj2

Numbers
0    1.5
1   -2.5
2    0.0
dtype: float64

In [186]:
obj2.index is labels

True

In [187]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [189]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [190]:
'Ohio' in frame3.columns

True

In [192]:
2003 in frame3.index

False

In [193]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [194]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [195]:
dup_labels.append

<bound method Index.append of Index(['foo', 'foo', 'bar', 'bar'], dtype='object')>

In [196]:
dup_labels.difference

<bound method Index.difference of Index(['foo', 'foo', 'bar', 'bar'], dtype='object')>

In [198]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index=['b','d','a','c'])

In [199]:
obj

b    4.5
d    7.2
a   -5.3
c    3.6
dtype: float64

In [202]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [203]:
obj2

a   -5.3
b    4.5
c    3.6
d    7.2
e    NaN
dtype: float64

In [204]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])

In [205]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [206]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [210]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index = ['a','c','d'],columns = ['Ohio', 'Texas', 'California'])

In [211]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [212]:
frame2 = frame.reindex(['a','b','c','d'])

In [213]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [219]:
states = ['Texas','Utah','California']

In [220]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [222]:
frame.loc[['a','b','c','d'], states]

/Users/harisx91/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [223]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])

In [224]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [225]:
new_obj = obj.drop('c')

In [226]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [228]:
obj.drop(['c','d'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [233]:
data = pd.DataFrame(np.arange(16).reshape(4,4), index = ['Ohio', 'Colorado','Utah','New York'], columns = ['one','two','three', 'four'])

In [234]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [235]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [236]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [238]:
data.drop(['two','four'], axis = 'columns' )

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [239]:
obj.drop('c', inplace=True)

In [240]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [241]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])

In [242]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [243]:
obj['b']

1.0

In [244]:
obj[1]

1.0

In [245]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [246]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [247]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [248]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [249]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [250]:
obj['b':'c'] = 5

In [251]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [256]:
data = pd.DataFrame(np.arange(16).reshape(4,4), index =["Ohio","Colorado","Utah","New York"], columns = ["one","two","three","four"])

In [257]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [258]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [259]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [260]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [262]:
data[1:]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [273]:
data[data['three']>3]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [274]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [275]:
data[data<5] = 0

In [276]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [279]:
data.loc["Colorado", ['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [280]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [281]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [285]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [288]:
data.loc[:'Colorado','two']

Ohio        0
Colorado    5
Name: two, dtype: int64

In [289]:
data.iloc[:, :3][data.three >5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14